name: damagemap-web
channels:
  - conda-forge
dependencies:
  - python=3.12
  - quarto
  - jupyter
  - ipykernel
  - nbclient
  - nbformat
  - pandas
  - pytz
  - geopandas
  - shapely
  - folium
  - branca
  - h3-py
